name: Clickhouse Cluster CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: docker-compose -f .docker-compose.yml-ci build --pull --no-cache
    - name: Bringup the environment
      run: docker-compose -f .docker-compose.yml-ci up -d
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: List all containers
      run: docker ps -a
    - name: Get  distributed cluster status
      run: if [ $(docker-compose exec -T click-one clickhouse-client -q "select count(*) from system.clusters where cluster = 'distributed';") -eq 2 ]; then echo "OK" || exit 0; fi
    - name: Get replicated cluster status
      run: if [ $(docker-compose exec -T click-one clickhouse-client -q "select count(*) from system.clusters where cluster = 'replicated';") -eq 2 ]; then echo "OK" || exit 0; fi
